# ===============================
# Swarm Simulator Configuration
# ===============================

# -------------------------------
# Arena / World Geometry
# -------------------------------
arena:
  # # arena size (m)
  # arena_size: 50
  # Minimum corner of the arena (x, y, z)
  min: [-10.0, -10.0, -10.0]
  # Maximum corner of the arena (x, y, z)
  max: [10.0, 10.0, 10.0]
  # Minimum distance between drones when randomizing start pos. [m]
  min_dist: 2
  randomize_init_pos: true
  # Cell size for the grid used for collision detection, nearest neighbor etc. [m]
  # Try to keep cell_size close to "interaction_radius". cell_size affects performance a lot
  cell_size: 20


# -------------------------------
# Target
# -------------------------------
target:
  position: [0.0, 0.0, 0.0]
  radius: 0.1


# -------------------------------
# Physics Parameters
# -------------------------------
physics:
  # Fixed simulation timestep (seconds)
  dt: 0.02
  # Maximum allowed velocity magnitude
  max_velocity: 5.0

# -------------------------------
# Sensing
# -------------------------------
sensing:
  # Max sensing distance, has to be smaller than 2*cell_size
  max_sensing: 50.0
  # nr_of_neighbors: 2  # Hard Coded for performance


# -------------------------------
# Collision Handling
# -------------------------------
collisions:
  # Collision radius per drone
  radius: 0.5
  # Disable drone immediately after collision
  # disable_on_hit: true

# -------------------------------
# Built-in Rule-Based Controllers
# -------------------------------
controllers:
  rule_based:
    # Enable simulator-owned drones
    enabled: true
    # Team ID controlled by simulator logic (e.g. opponent team)
    team_id: 1
    # Behavior name (mapped internally in Rust)
    behavior: "straight_flying"

# -------------------------------
# Logging Configuration
# -------------------------------
logging:
  # Enable episode logging
  enabled: true
  # Enable profiling
  profiling_enabled: false
  profiling_frequency: 1000 # Hz

# -------------------------------
# Debug / Development Options, TODO
# -------------------------------
debug:
  # Print simulator events to stdout
  verbose: true